[toolchain]
# Ensure builds are reproducible by locking the toolchain version
channel = "1.88.0"

# Always install these by default in CI (cargo, rustfmt, clippy)
components = ["cargo"]

# Automatically add required targets for your matrix
targets = [
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu"
]
