name: Publish Release

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

permissions:
  # TODO: publish attestations
  id-token: write
  attestations: write
  contents: write

env:
  TAG: ${{ github.ref_name }}
  GH_TOKEN: ${{ github.token }}

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Prepare workspace snippet
        run: .github/workflows/install_snippet.sh > release_notes.txt
      - run: gh release create "$TAG" --draft --generate-notes --notes-file release_notes.txt

  upload-assets:
    name: Build Rust binaries and upload to release
    needs: draft-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            ext: ''
          - target: aarch64-apple-darwin
            os: macos-latest
            ext: ''
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            ext: '.exe'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      # Use lightweight official Rust setup respecting rust-toolchain.toml
      - uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6

      # Optional: show Rust version for debugging
      - run: rustc --version && cargo --version

      # Build the release binary
      - name: Build release binary
        working-directory: pty-multiplex
        run: cargo build --release --target ${{ matrix.target }}

      # Upload to the existing draft release (created earlier)
      - name: Upload binary to GitHub Release
        working-directory: pty-multiplex
        shell: bash # Avoid PowerShell
        run: |
          BIN_NAME=pty-multiplex${{ matrix.ext }}
          BIN_PATH=target/${{ matrix.target }}/release/$BIN_NAME

          echo "Uploading $BIN_PATH..."
          gh release upload "$TAG" "$BIN_PATH" --clobber

  publish-release:
    runs-on: ubuntu-latest
    needs: upload-assets
    steps:
      - run: gh release edit "$TAG" --draft=false
